mongodb:
  image: 'mongo:3.4.10'
  volumes:
    - '{{ timestamp_file }}:{{ timestamp_file }}:ro'
    - '{{ timezone_file }}:{{ timezone_file }}:ro'
    - '{{ application_folder }}/backup:/backup'
    - '{{ application_folder }}/data:/data/db'

tomcat:
  image: 'chrisipa/cloud-portal-server:latest'
  links:
    - 'mongodb'
  volumes:
    - '{{ timestamp_file }}:{{ timestamp_file }}:ro'
    - '{{ timezone_file }}:{{ timezone_file }}:ro'
    - '{{ application_folder }}/trusted-certs:/opt/ssl/trusted:ro'
    - '{{ application_folder }}/logs:/opt/tomcat/logs'
  environment:
    - 'APPLICATION_TITLE={{ application_title }}'
    - 'APPLICATION_URL={{ application_url }}'
    - 'APPLICATION_DEV_MODE={{ application_dev_mode }}'
    - 'APPLICATION_ADMIN_GROUP={{ application_admin_group }}'
    - 'ENCRYPTOR_SECRET={{ encryptor_secret }}'
    - 'LDAP_BASE_DN={{ ldap_base_dn }}'
    - 'LDAP_GROUP_ATTRIBUTE={{ ldap_group_attribute }}'
    - 'LDAP_LOGIN_ATTRIBUTE={{ ldap_login_attribute }}'
    - 'LDAP_PASSWORD={{ ldap_password }}'
    - 'LDAP_PRINCIPAL={{ ldap_principal }}'
    - 'LDAP_URL_STRING={{ ldap_url_string }}'
    - 'LDAP_USER_SEARCH_FILTER={{ ldap_user_search_filter }}'
    - 'MAIL_FROM={{ mail_from }}'
    - 'MAIL_CC={{ mail_cc }}'
    - 'MAIL_HOST={{ mail_host }}'
    - 'MAIL_SEND={{ mail_send }}'
    - 'MONGO_DB_URI={{ mongo_db_uri }}'

apache:
  image: 'chrisipa/apache:latest'
  links:
    - 'tomcat'
  volumes:
    - '{{ timestamp_file }}:{{ timestamp_file }}:ro'
    - '{{ timezone_file }}:{{ timezone_file }}:ro'
    - '{{ application_folder }}/apache/vhosts.conf:/etc/apache2/conf-enabled/vhosts.conf:ro'
    - '{{ application_folder }}/ssl/{{ inventory_hostname }}:/opt/ssl/apache2'
    - '{{ application_folder }}/logs:/var/log/apache2'
  ports:
    - '{{ apache_http_port }}:{{ apache_http_port }}'
    - '{{ apache_https_port }}:{{ apache_https_port }}'
  environment:
    - 'AJP_HOST=tomcat'
    - 'AJP_PORT={{ tomcat_ajp_port }}'
    - 'SERVER_NAME={{ inventory_hostname }}'
    - 'SERVER_ALIAS={{ inventory_hostname }}'